import base64
import html
from pathlib import Path
from typing import Mapping, Sequence

from hikari_bot.core.constants import RESOURCES_DIR

from ..models import PriceChange
from ..parsing import rarity_jp_to_en

_TEMPLATE_DIR = Path(__file__).with_name("templates")
_PAGE_SIZE = 50
_OVERVIEW_SIZE = 30


def _load_background_url() -> str | None:
    resources = Path(RESOURCES_DIR)
    for extension in ("jpg", "jpeg", "png", "webp"):
        path = resources / f"bg_daily_report.{extension}"
        if path.exists():
            data = base64.b64encode(path.read_bytes()).decode()
            mime = (
                "image/jpeg"
                if extension in ("jpg", "jpeg")
                else f"image/{extension}"
            )
            return f"data:{mime};base64,{data}"
    return None


def _build_css(background_url: str | None) -> str:
    if background_url:
        background = (
            f"background-image: url('{background_url}'); "
            "background-size: cover; background-position: center center; "
            "background-repeat: no-repeat;"
        )
    else:
        background = (
            "background: linear-gradient("
            "160deg, #07091a 0%, #0c1528 40%, #07091a 100%);"
        )
    template = (_TEMPLATE_DIR / "daily_report.css").read_text(
        encoding="utf-8"
    )
    return template.replace("__PAGE_BACKGROUND__", background)


def _card_html(
    change: PriceChange,
    image_map: Mapping[int, str],
) -> str:
    name = html.escape(change.name)
    model_number = html.escape(change.model_number or "")
    rarity = html.escape(rarity_jp_to_en(change.rarity or ""))
    image_url = html.escape(
        image_map.get(change.product_id) or "",
        quote=True,
    )

    if change.change_type == "new":
        css_class = "new"
        badge = "新"
        old_html = '<div class="old-price">0円</div>'
    elif (change.price_diff or 0) > 0:
        css_class = "up"
        badge = "↑"
        old_html = (
            f'<div class="old-price">{change.old_price or 0:,}円</div>'
        )
    else:
        css_class = "down"
        badge = "↓"
        old_html = (
            f'<div class="old-price">{change.old_price:,}円</div>'
            if change.old_price
            else ""
        )

    return f"""
    <div class="card {css_class}">
      <img class="card-img" src="{image_url}" loading="lazy">
      <div class="card-overlay">
        <div class="card-name">{name}</div>
        <div class="card-meta">{model_number} {rarity}</div>
        <div class="price-row">
          <div class="price-block">
            <div class="new-price">{change.new_price:,}円</div>
            {old_html}
          </div>
          <span class="badge">{badge}</span>
        </div>
      </div>
    </div>"""


def _overview_score(change: PriceChange) -> float:
    return abs(change.percent_diff or 0) * (
        max(change.new_price or 1, 1) ** 0.5
    )


def _make_page_html(
    css: str,
    date_str: str,
    page_number_html: str,
    body_content: str,
) -> str:
    return f"""<!DOCTYPE html>
<html lang="zh">
<head>
<meta charset="UTF-8">
<style>{css}</style>
</head>
<body>
<div class="content-wrap">
  <div class="header">
    <div class="header-left">
      <div class="header-title">买取価格変動日報</div>
      <div class="header-eyebrow">CardRush · Daily Report</div>
    </div>
    <div class="header-right">
      <div class="header-date-main">{date_str[:4]}.{date_str[5:7]}.{date_str[8:10]}</div>
      {page_number_html}
    </div>
  </div>
  {body_content}
  <div class="watermark">Data by Cardrush &nbsp;/&nbsp; Generated by SRDS</div>
</div>
</body>
</html>"""


def render_daily_report_html(
    changes: Sequence[PriceChange],
    date_str: str,
    image_map: Mapping[int, str] | None = None,
    min_price: int = 0,
) -> list[str]:
    """Render one overview and zero or more 50-card detail HTML pages."""
    del min_price  # Retained for compatibility with the existing command API.
    if not changes:
        return []

    images = image_map or {}
    css = _build_css(_load_background_url())
    up_count = sum(
        1
        for change in changes
        if change.change_type == "changed"
        and (change.price_diff or 0) > 0
    )
    down_count = sum(
        1
        for change in changes
        if change.change_type == "changed"
        and (change.price_diff or 0) <= 0
    )
    new_count = sum(
        1 for change in changes if change.change_type == "new"
    )

    ranked = sorted(
        changes,
        key=_overview_score,
        reverse=True,
    )[:_OVERVIEW_SIZE]
    seen_ids = {change.product_id for change in ranked}
    content_changes = [
        change for change in changes if change.product_id not in seen_ids
    ]
    content_pages = (
        len(content_changes) + _PAGE_SIZE - 1
    ) // _PAGE_SIZE
    total_pages = content_pages + 1

    overview_cards = "".join(
        _card_html(change, images) for change in ranked
    )
    overview_cards += (
        '<div class="card card-placeholder"></div>'
        * (_OVERVIEW_SIZE - len(ranked))
    )
    date_display = (
        f"{date_str[:4]}年{date_str[5:7]}月{date_str[8:10]}日"
    )
    date_display_ja = (
        f"{date_str[:4]}年{int(date_str[5:7])}月"
        f"{int(date_str[8:10])}日"
    )
    chinese_summary = (
        f"统计了 <em>{date_display}</em> CardRush 平台买取价"
        f"<em>500円～100,000円</em>范围内游戏王单卡价格变动情况，"
        f"共 <em>{len(changes)}</em> 张卡发生变化。<br>"
        f"涨价 <em class='num-up'>{up_count}</em> 张　·　"
        f"降价 <em class='num-down'>{down_count}</em> 张　·　"
        f"新增 <em class='num-new'>{new_count}</em> 张"
    )
    japanese_summary = (
        f"<em>{date_display_ja}</em>のCardRushプラットフォームにおける"
        f"買取価格<em>500円〜100,000円</em>の遊戯王カード価格変動情報。"
        f"変動計 <em>{len(changes)}</em> 枚。<br>"
        f"値上がり <em class='num-up'>{up_count}</em> 枚　·　"
        f"値下がり <em class='num-down'>{down_count}</em> 枚　·　"
        f"新規 <em class='num-new'>{new_count}</em> 枚"
    )
    overview_body = f"""
  <div class="overview-extra">
    <div class="overview-desc">
      <div class="overview-desc-zh">{chinese_summary}</div>
      <div class="overview-desc-ja">{japanese_summary}</div>
    </div>
    <div class="overview-section-title"><span>異動 TOP {_OVERVIEW_SIZE}</span></div>
  </div>
  <div class="grid grid-overview">{overview_cards}
  </div>"""
    pages = [
        _make_page_html(
            css,
            date_str,
            f'<div class="header-page-num">PAGE 1/{total_pages}</div>',
            overview_body,
        )
    ]

    for page_index in range(content_pages):
        page = content_changes[
            page_index * _PAGE_SIZE : (page_index + 1) * _PAGE_SIZE
        ]
        cards = "".join(_card_html(change, images) for change in page)
        cards += (
            '<div class="card card-placeholder"></div>'
            * (_PAGE_SIZE - len(page))
        )
        pages.append(
            _make_page_html(
                css,
                date_str,
                (
                    '<div class="header-page-num">'
                    f"PAGE {page_index + 2}/{total_pages}</div>"
                ),
                f'<div class="grid">{cards}\n  </div>',
            )
        )
    return pages
